# Generated by Django 4.2.7 on 2026-04-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enrolled_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['id'],
            },
        ),
    ]
